# -*- coding: utf-8 -*-
"""
Created on Sun Jul  7 21:04:24 2019

@author: saadi
"""

#Sans séparateur
print("Date-Debut-experience: Septembre  2008\nDate-fin-experience: Septembre  2009\nDurée: 1 an\nintitule-experience: Ingénieur Etudes et Développement\nDesc-experience: Pilotage  des  projets , Optimiser l’usage de tous les composants de l’infrastructure , Mise en place de solution de haute disponibilité , Gestion des fichiers de configuration de base de données\nDate-Debut-experience: Janvier 2010\nDate-fin-experience: Octobre 2012\nDurée: 2 ans\nintitule-experience: Consultant études et développement\nDesc-experience: Mise en place et configuration Peplink , WAN Internet Link Load Balancing Routers , Mise en place d’un serveur mail en haute disponibilité\neducation: Master en Management des Systèmes d’Informations\neducation: Licence professionnelle Java/J2ee\neducation: BTS  option Génie Informatique\neducation: Baccalauréat sciences expérimentales\nprojet: Réalisation d’une application affichant des informations sur une ville\nprojet: Réalisation d’une application de gestion des employées\nprojet: Réalisation d’une application de gestion d’un club sportif\nprojet: Réalisation d’une application de gestion de logements\ncertificats: Certificat ISTQB ® niveau Foundation\ncertificats: IBM Certified specialist in FileNet Content Manager V5\ncertificats: IBM Certified specialist in FileNet Business Process Manager V5\ncertificats: IBM Datacap Taskmaster Capture Product Fundamentals Technical Professional\ncertificats: Certified ISO / IEC 2 0000 International Standard for IT Service Management\ncertificats: Certified COBIT Foundation V4\ncertificats: Training Project Management Professional\ncertificats: Training Resilia Cyber security resilience\nprofil: Senior IT Manager\nlangues: Arabe , Français , Anglais\ncompetence: Linux Ubuntu    \n competence: MS Dos, Win 2000\ncompetence: 2000 server\ncompetence: server/XP/Vista/7/8\ncompetence: XML/XSL, HTML/Javascript,Ajax, Servlet/JSP,Struts, JSF\ncompetence: Hibernate Spring JSTL HTTP  Php/MySQ\ncompetence: LDAP , Tomcat ,Glassfish,Websphére\ncompetence: Java , C#,VB net,Php\ncompetence: UML, Merise, Rational Rose, PowerAMC, Design Patterns\ncompetence: J2EE, EJB, JPA, JMS,MDB, NET, WebServices\ncompetence: TCP/IP, Topologies Réseaux")
#Avec séparateur     
#print("Date-Debut-experience: Septembre  2008]\nDate-fin-experience: Septembre  2009]\nDurée: 1 an]\nintitule-experience: Ingénieur Etudes et Développement]\nDesc-experience: Pilotage  des  projets , Optimiser l’usage de tous les composants de l’infrastructure , Mise en place de solution de haute disponibilité , Gestion des fichiers de configuration de base de données]\nDate-Debut-experience: Janvier 2010]\nDate-fin-experience: Octobre 2012]\nDurée: 2 ans]\nintitule-experience: Consultant études et développement]\nDesc-experience: Mise en place et configuration Peplink , WAN Internet Link Load Balancing Routers , Mise en place d’un serveur mail en haute disponibilité]\neducation: Master en Management des Systèmes d’Informations]\neducation: Licence professionnelle Java/J2ee]\neducation: BTS  option Génie Informatique]\neducation: Baccalauréat sciences expérimentales]\nprojet: Réalisation d’une application affichant des informations sur une ville]\nprojet: Réalisation d’une application de gestion des employées]\nprojet: Réalisation d’une application de gestion d’un club sportif]\nprojet: Réalisation d’une application de gestion de logements]\ncertificats: Certificat ISTQB ® niveau Foundation]\ncertificats: IBM Certified specialist in FileNet Content Manager V5]\ncertificats: IBM Certified specialist in FileNet Business Process Manager V5]\ncertificats: IBM Datacap Taskmaster Capture Product Fundamentals Technical Professional]\ncertificats: Certified ISO / IEC 2 0000 International Standard for IT Service Management]\ncertificats: Certified COBIT Foundation V4]\ncertificats: Training Project Management Professional]\ncertificats: Training Resilia Cyber security resilience]\nprofil: Senior IT Manager]\nlangues: Arabe , Français , Anglais]\ncompetence: Linux Ubuntu]\ncompetence: MS Dos, Win 2000]\ncompetence: 2000 server]\ncompetence: server/XP/Vista/7/8]\ncompetence: XML/XSL, HTML/Javascript,Ajax, Servlet/JSP,Struts, JSF]\ncompetence: Hibernate Spring JSTL HTTP  Php/MySQ]\ncompetence: LDAP , Tomcat ,Glassfish,Websphére]\ncompetence: Java , C#,VB net,Php]\ncompetence: UML, Merise, Rational Rose, PowerAMC, Design Patterns]\ncompetence: J2EE, EJB, JPA, JMS,MDB, NET, WebServices]\ncompetence: TCP/IP, Topologies Réseaux]")      